- hosts: all
  tasks:
    - name: remove exist file
      file:
        state: absent
        path: /home/ubuntu/node_nginx
      ignore_errors: true
    - name: Copy all
      copy:
        src: /home/ubuntu/workplace/node_nginx
        dest: /home/ubuntu
    - name: remove network first
      command: docker network rm jenkins-net
      ignore_errors: true
      # create the network for nginx vs nodejs
    - name: create docker network
      command: docker network create jenkins-net
      ignore_errors: false
    - name: run docker compose stop
      command: docker compose -f node_nginx/docker-compose.yml stop
      ignore_errors: false
    - name: run docker compose remove
      command: docker compose -f node_nginx/docker-compose.yml rm -f
      ignore_errors: false
    - name: run docker compose
      command: docker compose -f node_nginx/docker-compose.yml up --detach --build
      ignore_errors: false
