version: "3.9"

services:
  nodejs-app:
    build:
      context: ./jenkins-nodejs
    container_name: nodejs-server
    hostname: nodejs-server
    ports:
      - "3000:3000"
    networks:
      - jenkins-net
    stdin_open: true # docker run -i
    tty: true # docker run -t
  nginx:
    build:
      context: ./jenkins-nginx
    container_name: nginx
    hostname: nginx
    ports:
      # port server : port container 
      - "80:80"
    depends_on:
      - nodejs-app
    networks:
      - jenkins-net
    stdin_open: true # docker run -i
    tty: true # docker run -t
networks:
  jenkins-net:
    external: true
