version: "3.9"

services:
  nodejs-app:
    build:
      context: ./workplace/node_nginx/jenkins-nodejs
    container_name: nodejs-server
    hostname: nodejs-server
    ports:
      - "3000:3000"
    networks:
      - jenkins-net
  nginx:
    build:
      context: ./workplace/node_nginx/jenkins-nginx
    container_name: nginx
    hostname: nginx
    ports:
      # port server : port container 
      - "81:80"
    depends_on:
      - nodejs-app
    networks:
      - jenkins-net

networks:
  jenkin-net:
    external: true
